#!/usr/bin/python3
# 5-raise_exception.py

def raise_exception():
    print('{:d}'.format([1, 3, 4, 5]))
